### ISSUE TITLE
abort causes error handler to fire

### ISSUE THREAD

**Issue by mrkam** [eBay/jsonpipe#13]
Executing xhr.abort() on the XMLHttpRequest returned by flow() method will trigger its error method without any indication of the request being aborted.

A workaround is to add onabort and onerror after flow() method and not use error inside the flow method settings. In that case abort will only cause onabort handler to execute.

Observed with Chrome v. 54.

**Comment by senthilp** [comment]
The problem is the error handler will not be invoked even if the network is offline. The `xhr.status === 0` is true for both abort and offline, so we will not be able to call error function if we do this check. Also `onreadystatechange` is called before `onabort` so I will not be able to know if the actual error was abort. A way to fix this to create a wrapper on XHR, that will make the utility more complex.

Another option is for the consuming application to attach `xhr.onabort` handler and also do a check in the `error` function for `xhr.status === 0` and ignore it. In that case only the `onabort` handler will be executed.
